// src/app/auth/login/page.tsx
import Logo from '@/app/(DashboardLayout)/layout/shared/logo/Logo';
import React, { Suspense } from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';
import AuthLogin from '../authforms/AuthLogin';

export const metadata: Metadata = {
  title: 'Login Authentication',
  description: 'Generated by create next app',
};

// Loading component for Suspense fallback
const AuthLoginLoading = () => (
  <div className='p-4 rounded-md bg-gray-100 animate-pulse'>
    <div className='h-8 bg-gray-200 rounded mb-4'></div>
    <div className='h-8 bg-gray-200 rounded mb-4'></div>
    <div className='h-8 bg-gray-200 rounded'></div>
  </div>
);

const BoxedLogin = () => {
  return (
    <>
      <div className='relative overflow-hidden h-screen bg-muted dark:bg-dark'>
        <div className='flex h-full justify-center items-center px-4'>
          <div className='rounded-lg dark:shadow-dark-md shadow-md bg-white dark:bg-darkgray p-6 relative w-full md:w-[450px] break-words border-none'>
            <div className='flex h-full flex-col justify-center gap-2 p-0 w-full'>
              <div className='mx-auto'>
                <Logo />
              </div>
              <p className='text-sm text-center text-dark my-3'>Selamat Datang Kembali</p>

              {/* Wrap AuthLogin in Suspense to handle useSearchParams */}
              <Suspense fallback={<AuthLoginLoading />}>
                <AuthLogin />
              </Suspense>

              <div className='flex gap-2 text-base text-ld font-medium mt-6 items-center justify-center'>
                <p>Belum memiliki akun?</p>
                <Link href={'/auth/register'} className='text-primary text-sm font-medium'>
                  Buat Akun
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default BoxedLogin;
